### ISSUE TITLE
Not working with Fuji RAF files

### ISSUE THREAD

**Issue by pieterclaerhout** [mz2/Carpaccio#6]
I've tried using your library with Fuji .RAF files and it failed to load the image metadata.

Adding "raf" to the list of RAWImageFileExtensions seems to fix the problem.

Any chance you can add this?

**Comment by mz2** [comment]
Sure, absolutely, but it would be also nice to have at least one example image and a test. Would you mind posting these as a PR, please?

Matias

- - - - -
Matias Piipari, PhD
http://twitter.com/mz2

Manuscripts - A writing tool like nothing you have seen before
http://manuscriptsapp.com

**Comment by pieterclaerhout** [comment]
Will do.

**Comment by pieterclaerhout** [comment]
Hi Matias,

there is actually an online repository containing all kinds of different raw files which you can use for testing:

https://raw.pixls.us

The repo is too big to check in to GitHub...

**Comment by mz2** [comment]
Nice one, I was not aware of this resource. A larger resource like this list this sounds like something we could include a script for some separate integration tests with, not necessarily run on every commit – I've recently added a command line target (`carpaccio-dump`) to the repo which may be a simple way to test with a larger pool of images as well (to check that metadata like size, camera model etc were parsed out correctly from all the files).

As you might have guessed we have intentionally added the file extension list "whitelist" in the app so that we only add support for file types we have at least one example of. It may be a time to lift this restriction pretty soon, especially as the library is now reporting pretty informative errors instead of crashing also when it fails to unexpectedly decode an image (it can fail at various stages of the decoding and metadata extraction stages).

**Comment by pieterclaerhout** [comment]
Well, given the fact that the complete raw repo is about 9 GB, it wouldn't be practical to run it on every commit.

I'm all for removing the whitelist and let the library handle the errors properly.

**Comment by mz2** [comment]
Maybe it's actually not such a crazy idea – it's just about 580 images, testing that metadata parsing doesn't lose something obvious for example would be very fast and still doable per commit, and would easily work with the CI setup we have set up for the project at https://gitlab.com/sashimiapp-public/Carpaccio . Anyway, I propose a trade: if you commit a test for an example Fuji image, or even better two in different orientations for example, I'll happily drop the limit on those file extensions and try adding a separate test script that uses `carpaccio-dump` (a command line tool I added into the repo recently) and run some basic checks on the image metadata extracted.

**Comment by pieterclaerhout** [comment]
The only thing I've noticed is that it doesn't report the nativeSize correctly for Fuji RAW files...

**Comment by mz2** [comment]
This is kind of the reason we've been going about this carefully. We also hit some oddities with Canon RAWs (they also have some inconsistencies with metadata vs actual sizing). If you can indeed confirm it's wrong (by means of comparing to some other metadata reporting method), I'm happy to take that as a bug report (after the expected size is asserted in the tests that should therefore fail) and try to work out why we may be reporting the wrong value.

**Comment by pieterclaerhout** [comment]
I'll update the test so that it checks the correct size and I'll see if I can figure out why it's wrong.

**Comment by pieterclaerhout** [comment]
I've updated the pull request so that the native width and height for Fujifilm files is now correct.

**Comment by mz2** [comment]
Thanks for addressing this – forgot to close the issue at the time.
